# token密钥
SECRET_KEY: "b7a9563b93f709f4caa6cf63be75e094faa9d288e8d36ca259f6f056c818166"
ALGORITHM: "HS256"
# token过期时间
ACCESS_TOKEN_EXPIRE_MINUTES: 1440

# 默认管理员
Default_Administrator: 'admin'
# 默认密码
Default_Passwd: 'nHYjlSm773RlLq'
# mysql数据库信息
databases:
    host: 127.0.0.1
    username: root
    password: 123456
    port: 3306
    dbname: blog
    echo: true

# fastapi
fastapi:
    host: 127.0.0.1
    port: 8000
    reload: true



